[book]
title = "Koj language reference"
description = "This site is the reference for the Koj programming language"
authors = ["Tom Béné"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/koj-lang/reference"